// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// CreateConversationParams holds parameters for CreateConversation.
type CreateConversationParams struct {
	ItemID   uuid.UUID `json:"item_id"`
	OwnerID  uuid.UUID `json:"owner_id"`
	RenterID uuid.UUID `json:"renter_id"`
}

// SendMessageParams holds parameters for SendMessage.
type SendMessageParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderID       uuid.UUID `json:"sender_id"`
	Body           string    `json:"body"`
}

// ItemChatInfoRow contains the item fields needed to start a conversation.
type ItemChatInfoRow struct {
	ItemID      uuid.UUID      `json:"item_id"`
	OwnerID     uuid.UUID      `json:"owner_id"`
	Title       string         `json:"title"`
	PricePerDay pgtype.Numeric `json:"price_per_day"`
}

// ConversationRow contains all fields needed by the conversation list UI.
type ConversationRow struct {
	ConversationID uuid.UUID          `json:"conversation_id"`
	ItemID         uuid.UUID          `json:"item_id"`
	ItemTitle      string             `json:"item_title"`
	ItemPrice      pgtype.Numeric     `json:"item_price"`
	OtherUserID    uuid.UUID          `json:"other_user_id"`
	OtherUserName  string             `json:"other_user_name"`
	OtherAvatarURL string             `json:"other_avatar_url"`
	LastMessage    string             `json:"last_message"`
	LastMessageAt  pgtype.Timestamptz `json:"last_message_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// MessageRow contains a message and its timestamps.
type MessageRow struct {
	MessageID      uuid.UUID          `json:"message_id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	SenderID       uuid.UUID          `json:"sender_id"`
	Body           string             `json:"body"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	IsRead         bool               `json:"is_read"`
}

const getItemChatInfo = `
SELECT item_id, owner_id, title, price_per_day
FROM item
WHERE item_id = $1
LIMIT 1
`

// GetItemChatInfo returns item data needed to start a chat.
func (q *Queries) GetItemChatInfo(ctx context.Context, itemID uuid.UUID) (ItemChatInfoRow, error) {
	row := q.db.QueryRow(ctx, getItemChatInfo, itemID)
	var i ItemChatInfoRow
	err := row.Scan(&i.ItemID, &i.OwnerID, &i.Title, &i.PricePerDay)
	return i, err
}

const createConversation = `
INSERT INTO conversation (item_id, customer_1_id, customer_2_id)
VALUES ($1, $2, $3)
ON CONFLICT (customer_1_id, customer_2_id, item_id)
DO UPDATE SET item_id = conversation.item_id
RETURNING conversation_id
`

// CreateConversation creates a conversation or returns the existing one.
func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.ItemID, arg.OwnerID, arg.RenterID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listConversations = `
SELECT
    c.conversation_id,
    c.item_id,
    i.title AS item_title,
    i.price_per_day AS item_price,
    other_user.customer_id AS other_user_id,
    other_user.first_name || ' ' || other_user.last_name AS other_user_name,
    COALESCE(other_user.avatar_url, '') AS other_avatar_url,
    COALESCE(last_msg.content, '') AS last_message,
    last_msg.sent_at AS last_message_at,
    c.created_at
FROM conversation c
JOIN item i ON i.item_id = c.item_id
JOIN customer other_user ON other_user.customer_id = CASE
    WHEN c.customer_1_id = $1 THEN c.customer_2_id
    ELSE c.customer_1_id
END
LEFT JOIN LATERAL (
    SELECT content, sent_at
    FROM message
    WHERE conversation_id = c.conversation_id
    ORDER BY sent_at DESC, message_id DESC
    LIMIT 1
) last_msg ON true
WHERE c.customer_1_id = $1 OR c.customer_2_id = $1
ORDER BY COALESCE(last_msg.sent_at, c.created_at) DESC
`

// ListConversations returns conversations visible to the current user.
func (q *Queries) ListConversations(ctx context.Context, customerID uuid.UUID) ([]ConversationRow, error) {
	rows, err := q.db.Query(ctx, listConversations, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	conversations := make([]ConversationRow, 0)
	for rows.Next() {
		var row ConversationRow
		if err := rows.Scan(
			&row.ConversationID,
			&row.ItemID,
			&row.ItemTitle,
			&row.ItemPrice,
			&row.OtherUserID,
			&row.OtherUserName,
			&row.OtherAvatarURL,
			&row.LastMessage,
			&row.LastMessageAt,
			&row.UpdatedAt,
		); err != nil {
			return nil, err
		}
		conversations = append(conversations, row)
	}

	return conversations, rows.Err()
}

const getConversation = `
SELECT
    c.conversation_id,
    c.item_id,
    i.title AS item_title,
    i.price_per_day AS item_price,
    other_user.customer_id AS other_user_id,
    other_user.first_name || ' ' || other_user.last_name AS other_user_name,
    COALESCE(other_user.avatar_url, '') AS other_avatar_url,
    COALESCE(last_msg.content, '') AS last_message,
    last_msg.sent_at AS last_message_at,
    c.created_at
FROM conversation c
JOIN item i ON i.item_id = c.item_id
JOIN customer other_user ON other_user.customer_id = CASE
    WHEN c.customer_1_id = $2 THEN c.customer_2_id
    ELSE c.customer_1_id
END
LEFT JOIN LATERAL (
    SELECT content, sent_at
    FROM message
    WHERE conversation_id = c.conversation_id
    ORDER BY sent_at DESC, message_id DESC
    LIMIT 1
) last_msg ON true
WHERE c.conversation_id = $1
  AND (c.customer_1_id = $2 OR c.customer_2_id = $2)
LIMIT 1
`

// GetConversation returns a conversation if the current user participates in it.
func (q *Queries) GetConversation(ctx context.Context, conversationID, customerID uuid.UUID) (ConversationRow, error) {
	row := q.db.QueryRow(ctx, getConversation, conversationID, customerID)
	var c ConversationRow
	err := row.Scan(
		&c.ConversationID,
		&c.ItemID,
		&c.ItemTitle,
		&c.ItemPrice,
		&c.OtherUserID,
		&c.OtherUserName,
		&c.OtherAvatarURL,
		&c.LastMessage,
		&c.LastMessageAt,
		&c.UpdatedAt,
	)
	return c, err
}

const sendMessage = `
INSERT INTO message (conversation_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING message_id, conversation_id, sender_id, content, NULL::timestamptz AS read_at, sent_at, is_read
`

// SendMessage appends a message to a conversation.
func (q *Queries) SendMessage(ctx context.Context, arg SendMessageParams) (MessageRow, error) {
	row := q.db.QueryRow(ctx, sendMessage, arg.ConversationID, arg.SenderID, arg.Body)
	var m MessageRow
	err := row.Scan(&m.MessageID, &m.ConversationID, &m.SenderID, &m.Body, &m.ReadAt, &m.CreatedAt, &m.IsRead)
	return m, err
}

const listMessages = `
SELECT message_id, conversation_id, sender_id, content, NULL::timestamptz AS read_at, sent_at, is_read
FROM message
WHERE conversation_id = $1
ORDER BY sent_at ASC, message_id ASC
`

// ListMessages returns all messages in a conversation, oldest first.
func (q *Queries) ListMessages(ctx context.Context, conversationID uuid.UUID) ([]MessageRow, error) {
	rows, err := q.db.Query(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	messages := make([]MessageRow, 0)
	for rows.Next() {
		var m MessageRow
		if err := rows.Scan(&m.MessageID, &m.ConversationID, &m.SenderID, &m.Body, &m.ReadAt, &m.CreatedAt, &m.IsRead); err != nil {
			return nil, err
		}
		messages = append(messages, m)
	}

	return messages, rows.Err()
}

const touchConversation = `
SELECT 1
`

// TouchConversation refreshes a conversation's ordering timestamp.
func (q *Queries) TouchConversation(ctx context.Context, conversationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchConversation)
	return err
}

const markMessagesRead = `
UPDATE message
SET is_read = true
WHERE conversation_id = $1
  AND sender_id <> $2
  AND is_read = false
RETURNING message_id
`

// MarkMessagesRead marks unread messages from the other participant as read.
func (q *Queries) MarkMessagesRead(ctx context.Context, conversationID, readerID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, markMessagesRead, conversationID, readerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	messageIDs := make([]uuid.UUID, 0)
	for rows.Next() {
		var messageID uuid.UUID
		if err := rows.Scan(&messageID); err != nil {
			return nil, err
		}
		messageIDs = append(messageIDs, messageID)
	}

	return messageIDs, rows.Err()
}
