// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomers = `-- name: CountCustomers :one
SELECT COUNT(*) FROM customer
`

func (q *Queries) CountCustomers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one

INSERT INTO customer (
    first_name,
    last_name,
    email,
    phone,
    password_hash,
    user_role,
    avatar_url,
    stripe_customer_id
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8
         )
RETURNING
    customer_id,
    first_name,
    last_name,
    email,
    phone,
    avatar_url,
    registration_date,
    account_status,
    user_role,
    stripe_customer_id
`

type CreateCustomerParams struct {
	FirstName        string      `json:"first_name"`
	LastName         string      `json:"last_name"`
	Email            string      `json:"email"`
	Phone            pgtype.Text `json:"phone"`
	PasswordHash     string      `json:"password_hash"`
	UserRole         UserRole    `json:"user_role"`
	AvatarUrl        pgtype.Text `json:"avatar_url"`
	StripeCustomerID pgtype.Text `json:"stripe_customer_id"`
}

type CreateCustomerRow struct {
	CustomerID       uuid.UUID          `json:"customer_id"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	Email            string             `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	RegistrationDate pgtype.Timestamptz `json:"registration_date"`
	AccountStatus    AccountStatus      `json:"account_status"`
	UserRole         UserRole           `json:"user_role"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
}

// ============================================
// CREATE
// ============================================
func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (CreateCustomerRow, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.UserRole,
		arg.AvatarUrl,
		arg.StripeCustomerID,
	)
	var i CreateCustomerRow
	err := row.Scan(
		&i.CustomerID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.AvatarUrl,
		&i.RegistrationDate,
		&i.AccountStatus,
		&i.UserRole,
		&i.StripeCustomerID,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec

DELETE FROM customer
WHERE customer_id = $1
`

// ============================================
// DELETE
// ============================================
func (q *Queries) DeleteCustomer(ctx context.Context, customerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCustomer, customerID)
	return err
}

const existsCustomerByEmail = `-- name: ExistsCustomerByEmail :one
SELECT EXISTS (
    SELECT 1 FROM customer WHERE email = $1
) AS email_exists
`

func (q *Queries) ExistsCustomerByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, existsCustomerByEmail, email)
	var email_exists bool
	err := row.Scan(&email_exists)
	return email_exists, err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT
    customer_id,
    first_name,
    last_name,
    email,
    phone,
    password_hash,
    avatar_url,
    registration_date,
    account_status,
    user_role,
    stripe_customer_id
FROM customer
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.CustomerID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.RegistrationDate,
		&i.AccountStatus,
		&i.UserRole,
		&i.StripeCustomerID,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one

SELECT
    customer_id,
    first_name,
    last_name,
    email,
    phone,
    avatar_url,
    registration_date,
    account_status,
    user_role,
    stripe_customer_id
FROM customer
WHERE customer_id = $1
LIMIT 1
`

type GetCustomerByIDRow struct {
	CustomerID       uuid.UUID          `json:"customer_id"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	Email            string             `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	RegistrationDate pgtype.Timestamptz `json:"registration_date"`
	AccountStatus    AccountStatus      `json:"account_status"`
	UserRole         UserRole           `json:"user_role"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
}

// ============================================
// READ
// ============================================
func (q *Queries) GetCustomerByID(ctx context.Context, customerID uuid.UUID) (GetCustomerByIDRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, customerID)
	var i GetCustomerByIDRow
	err := row.Scan(
		&i.CustomerID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.AvatarUrl,
		&i.RegistrationDate,
		&i.AccountStatus,
		&i.UserRole,
		&i.StripeCustomerID,
	)
	return i, err
}

const getCustomerByStripeID = `-- name: GetCustomerByStripeID :one
SELECT
    customer_id,
    first_name,
    last_name,
    email,
    phone,
    avatar_url,
    registration_date,
    account_status,
    user_role,
    stripe_customer_id
FROM customer
WHERE stripe_customer_id = $1
LIMIT 1
`

type GetCustomerByStripeIDRow struct {
	CustomerID       uuid.UUID          `json:"customer_id"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	Email            string             `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	RegistrationDate pgtype.Timestamptz `json:"registration_date"`
	AccountStatus    AccountStatus      `json:"account_status"`
	UserRole         UserRole           `json:"user_role"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
}

func (q *Queries) GetCustomerByStripeID(ctx context.Context, stripeCustomerID pgtype.Text) (GetCustomerByStripeIDRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByStripeID, stripeCustomerID)
	var i GetCustomerByStripeIDRow
	err := row.Scan(
		&i.CustomerID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.AvatarUrl,
		&i.RegistrationDate,
		&i.AccountStatus,
		&i.UserRole,
		&i.StripeCustomerID,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT
    customer_id,
    first_name,
    last_name,
    email,
    phone,
    avatar_url,
    registration_date,
    account_status,
    user_role,
    stripe_customer_id
FROM customer
ORDER BY registration_date DESC
LIMIT $1 OFFSET $2
`

type ListCustomersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListCustomersRow struct {
	CustomerID       uuid.UUID          `json:"customer_id"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	Email            string             `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	RegistrationDate pgtype.Timestamptz `json:"registration_date"`
	AccountStatus    AccountStatus      `json:"account_status"`
	UserRole         UserRole           `json:"user_role"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomersRow
	for rows.Next() {
		var i ListCustomersRow
		if err := rows.Scan(
			&i.CustomerID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.AvatarUrl,
			&i.RegistrationDate,
			&i.AccountStatus,
			&i.UserRole,
			&i.StripeCustomerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersByStatus = `-- name: ListCustomersByStatus :many
SELECT
    customer_id,
    first_name,
    last_name,
    email,
    phone,
    avatar_url,
    registration_date,
    account_status,
    user_role,
    stripe_customer_id
FROM customer
WHERE account_status = $1
ORDER BY registration_date DESC
LIMIT $2 OFFSET $3
`

type ListCustomersByStatusParams struct {
	AccountStatus AccountStatus `json:"account_status"`
	Limit         int32         `json:"limit"`
	Offset        int32         `json:"offset"`
}

type ListCustomersByStatusRow struct {
	CustomerID       uuid.UUID          `json:"customer_id"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	Email            string             `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	RegistrationDate pgtype.Timestamptz `json:"registration_date"`
	AccountStatus    AccountStatus      `json:"account_status"`
	UserRole         UserRole           `json:"user_role"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
}

func (q *Queries) ListCustomersByStatus(ctx context.Context, arg ListCustomersByStatusParams) ([]ListCustomersByStatusRow, error) {
	rows, err := q.db.Query(ctx, listCustomersByStatus, arg.AccountStatus, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomersByStatusRow
	for rows.Next() {
		var i ListCustomersByStatusRow
		if err := rows.Scan(
			&i.CustomerID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.AvatarUrl,
			&i.RegistrationDate,
			&i.AccountStatus,
			&i.UserRole,
			&i.StripeCustomerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCustomers = `-- name: SearchCustomers :many
SELECT
    customer_id,
    first_name,
    last_name,
    email,
    phone,
    avatar_url,
    registration_date,
    account_status,
    user_role,
    stripe_customer_id
FROM customer
WHERE
    first_name ILIKE $1
OR last_name ILIKE $1
OR email ILIKE $1
ORDER BY registration_date DESC
LIMIT $2 OFFSET $3
`

type SearchCustomersParams struct {
	FirstName string `json:"first_name"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type SearchCustomersRow struct {
	CustomerID       uuid.UUID          `json:"customer_id"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	Email            string             `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	RegistrationDate pgtype.Timestamptz `json:"registration_date"`
	AccountStatus    AccountStatus      `json:"account_status"`
	UserRole         UserRole           `json:"user_role"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
}

func (q *Queries) SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]SearchCustomersRow, error) {
	rows, err := q.db.Query(ctx, searchCustomers, arg.FirstName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCustomersRow
	for rows.Next() {
		var i SearchCustomersRow
		if err := rows.Scan(
			&i.CustomerID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.AvatarUrl,
			&i.RegistrationDate,
			&i.AccountStatus,
			&i.UserRole,
			&i.StripeCustomerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCustomer = `-- name: SoftDeleteCustomer :exec
UPDATE customer
SET account_status = 'inactive'
WHERE customer_id = $1
`

func (q *Queries) SoftDeleteCustomer(ctx context.Context, customerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCustomer, customerID)
	return err
}

const updateCustomerAvatar = `-- name: UpdateCustomerAvatar :exec
UPDATE customer
SET avatar_url = $2
WHERE customer_id = $1
`

type UpdateCustomerAvatarParams struct {
	CustomerID uuid.UUID   `json:"customer_id"`
	AvatarUrl  pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateCustomerAvatar(ctx context.Context, arg UpdateCustomerAvatarParams) error {
	_, err := q.db.Exec(ctx, updateCustomerAvatar, arg.CustomerID, arg.AvatarUrl)
	return err
}

const updateCustomerEmail = `-- name: UpdateCustomerEmail :one
UPDATE customer
SET email = $2
WHERE customer_id = $1
RETURNING customer_id, email
`

type UpdateCustomerEmailParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	Email      string    `json:"email"`
}

type UpdateCustomerEmailRow struct {
	CustomerID uuid.UUID `json:"customer_id"`
	Email      string    `json:"email"`
}

func (q *Queries) UpdateCustomerEmail(ctx context.Context, arg UpdateCustomerEmailParams) (UpdateCustomerEmailRow, error) {
	row := q.db.QueryRow(ctx, updateCustomerEmail, arg.CustomerID, arg.Email)
	var i UpdateCustomerEmailRow
	err := row.Scan(&i.CustomerID, &i.Email)
	return i, err
}

const updateCustomerPassword = `-- name: UpdateCustomerPassword :exec
UPDATE customer
SET password_hash = $2
WHERE customer_id = $1
`

type UpdateCustomerPasswordParams struct {
	CustomerID   uuid.UUID `json:"customer_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateCustomerPassword(ctx context.Context, arg UpdateCustomerPasswordParams) error {
	_, err := q.db.Exec(ctx, updateCustomerPassword, arg.CustomerID, arg.PasswordHash)
	return err
}

const updateCustomerProfile = `-- name: UpdateCustomerProfile :one

UPDATE customer
SET
    first_name = $2,
last_name  = $3,
phone      = $4,
avatar_url = $5
WHERE customer_id = $1
RETURNING
    customer_id,
    first_name,
    last_name,
    email,
    phone,
    avatar_url,
    registration_date,
    account_status,
    user_role,
    stripe_customer_id
`

type UpdateCustomerProfileParams struct {
	CustomerID uuid.UUID   `json:"customer_id"`
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	Phone      pgtype.Text `json:"phone"`
	AvatarUrl  pgtype.Text `json:"avatar_url"`
}

type UpdateCustomerProfileRow struct {
	CustomerID       uuid.UUID          `json:"customer_id"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	Email            string             `json:"email"`
	Phone            pgtype.Text        `json:"phone"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	RegistrationDate pgtype.Timestamptz `json:"registration_date"`
	AccountStatus    AccountStatus      `json:"account_status"`
	UserRole         UserRole           `json:"user_role"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
}

// ============================================
// UPDATE
// ============================================
func (q *Queries) UpdateCustomerProfile(ctx context.Context, arg UpdateCustomerProfileParams) (UpdateCustomerProfileRow, error) {
	row := q.db.QueryRow(ctx, updateCustomerProfile,
		arg.CustomerID,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.AvatarUrl,
	)
	var i UpdateCustomerProfileRow
	err := row.Scan(
		&i.CustomerID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.AvatarUrl,
		&i.RegistrationDate,
		&i.AccountStatus,
		&i.UserRole,
		&i.StripeCustomerID,
	)
	return i, err
}

const updateCustomerRole = `-- name: UpdateCustomerRole :one
UPDATE customer
SET user_role = $2
WHERE customer_id = $1
RETURNING customer_id, user_role
`

type UpdateCustomerRoleParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	UserRole   UserRole  `json:"user_role"`
}

type UpdateCustomerRoleRow struct {
	CustomerID uuid.UUID `json:"customer_id"`
	UserRole   UserRole  `json:"user_role"`
}

func (q *Queries) UpdateCustomerRole(ctx context.Context, arg UpdateCustomerRoleParams) (UpdateCustomerRoleRow, error) {
	row := q.db.QueryRow(ctx, updateCustomerRole, arg.CustomerID, arg.UserRole)
	var i UpdateCustomerRoleRow
	err := row.Scan(&i.CustomerID, &i.UserRole)
	return i, err
}

const updateCustomerStatus = `-- name: UpdateCustomerStatus :one
UPDATE customer
SET account_status = $2
WHERE customer_id = $1
RETURNING customer_id, account_status
`

type UpdateCustomerStatusParams struct {
	CustomerID    uuid.UUID     `json:"customer_id"`
	AccountStatus AccountStatus `json:"account_status"`
}

type UpdateCustomerStatusRow struct {
	CustomerID    uuid.UUID     `json:"customer_id"`
	AccountStatus AccountStatus `json:"account_status"`
}

func (q *Queries) UpdateCustomerStatus(ctx context.Context, arg UpdateCustomerStatusParams) (UpdateCustomerStatusRow, error) {
	row := q.db.QueryRow(ctx, updateCustomerStatus, arg.CustomerID, arg.AccountStatus)
	var i UpdateCustomerStatusRow
	err := row.Scan(&i.CustomerID, &i.AccountStatus)
	return i, err
}

const updateCustomerStripeID = `-- name: UpdateCustomerStripeID :exec
UPDATE customer
SET stripe_customer_id = $2
WHERE customer_id = $1
`

type UpdateCustomerStripeIDParams struct {
	CustomerID       uuid.UUID   `json:"customer_id"`
	StripeCustomerID pgtype.Text `json:"stripe_customer_id"`
}

func (q *Queries) UpdateCustomerStripeID(ctx context.Context, arg UpdateCustomerStripeIDParams) error {
	_, err := q.db.Exec(ctx, updateCustomerStripeID, arg.CustomerID, arg.StripeCustomerID)
	return err
}
