// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorite.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec

INSERT INTO favorite (customer_id, item_id)
VALUES ($1, $2)
ON CONFLICT (customer_id, item_id) DO NOTHING
`

type AddFavoriteParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	ItemID     uuid.UUID `json:"item_id"`
}

// ============================================
// CREATE / DELETE
// ============================================
func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.CustomerID, arg.ItemID)
	return err
}

const isFavorite = `-- name: IsFavorite :one

SELECT EXISTS (
    SELECT 1 FROM favorite
    WHERE customer_id = $1 AND item_id = $2
) AS is_favorite
`

type IsFavoriteParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	ItemID     uuid.UUID `json:"item_id"`
}

// ============================================
// READ
// ============================================
func (q *Queries) IsFavorite(ctx context.Context, arg IsFavoriteParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFavorite, arg.CustomerID, arg.ItemID)
	var is_favorite bool
	err := row.Scan(&is_favorite)
	return is_favorite, err
}

const listFavoriteItems = `-- name: ListFavoriteItems :many
SELECT
    i.item_id,
    i.category,
    i.title,
    i.item_status,
    i.price_per_day,
    i.is_available,
    a.city,
    COALESCE(img.image_url, '') AS primary_image_url,
    f.saved_at
FROM favorite f
JOIN item i ON i.item_id = f.item_id
JOIN address a ON a.address_id = i.address_id
LEFT JOIN LATERAL (
    SELECT image_url
    FROM item_image
    WHERE item_id = i.item_id
    ORDER BY display_order ASC, image_id ASC
    LIMIT 1
) img ON true
WHERE f.customer_id = $1
ORDER BY f.saved_at DESC
`

type ListFavoriteItemsRow struct {
	ItemID          uuid.UUID          `json:"item_id"`
	Category        CategoryEnum       `json:"category"`
	Title           string             `json:"title"`
	ItemStatus      ItemStatus         `json:"item_status"`
	PricePerDay     pgtype.Numeric     `json:"price_per_day"`
	IsAvailable     bool               `json:"is_available"`
	City            string             `json:"city"`
	PrimaryImageUrl string             `json:"primary_image_url"`
	SavedAt         pgtype.Timestamptz `json:"saved_at"`
}

func (q *Queries) ListFavoriteItems(ctx context.Context, customerID uuid.UUID) ([]ListFavoriteItemsRow, error) {
	rows, err := q.db.Query(ctx, listFavoriteItems, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoriteItemsRow
	for rows.Next() {
		var i ListFavoriteItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Category,
			&i.Title,
			&i.ItemStatus,
			&i.PricePerDay,
			&i.IsAvailable,
			&i.City,
			&i.PrimaryImageUrl,
			&i.SavedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorite
WHERE customer_id = $1 AND item_id = $2
`

type RemoveFavoriteParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	ItemID     uuid.UUID `json:"item_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.CustomerID, arg.ItemID)
	return err
}
