// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

const searchItemCards = `
SELECT
    i.item_id,
    i.owner_id,
    i.address_id,
    i.category,
    i.title,
    i.item_status,
    i.price_per_day,
    i.is_available,
    i.published_at,
    a.city,
    img.image_url AS primary_image_url,
    c.first_name  AS owner_first_name,
    c.last_name   AS owner_last_name,
    COALESCE(c.avatar_url, '') AS owner_avatar_url,
    COUNT(*) OVER() AS total_count
FROM item i
JOIN address  a ON a.address_id  = i.address_id
JOIN customer c ON c.customer_id = i.owner_id
LEFT JOIN LATERAL (
    SELECT image_url
    FROM item_image
    WHERE item_id = i.item_id
    ORDER BY display_order , image_id
    LIMIT 1
) img ON true
WHERE ($1 = false OR i.is_available = true)
  AND (
    $2 = ''
    OR i.title ILIKE '%' || $2 || '%'
    OR COALESCE(i.description, '') ILIKE '%' || $2 || '%'
  )
  AND ($3 = '' OR i.category::text = $3)
  AND ($4 = '' OR a.city ILIKE $4)
  AND ($5 = '' OR i.item_condition::text = $5)
  AND ($6::numeric IS NULL OR i.price_per_day >= $6::numeric)
  AND ($7::numeric IS NULL OR i.price_per_day <= $7::numeric)
ORDER BY
    CASE WHEN $8 = 'price_asc' THEN i.price_per_day END ,
    CASE WHEN $8 = 'price_desc' THEN i.price_per_day END DESC,
    CASE WHEN $8 = 'oldest' THEN i.published_at END ,
    i.published_at DESC
LIMIT $9 OFFSET $10
`

// SearchItemCardsParams defines filters and pagination for SearchItemCards.
type SearchItemCardsParams struct {
	RequireAvailable bool     `json:"require_available"`
	Query            string   `json:"query"`
	Category         string   `json:"category"`
	City             string   `json:"city"`
	Condition        string   `json:"condition"`
	MinPrice         *float64 `json:"min_price"`
	MaxPrice         *float64 `json:"max_price"`
	Sort             string   `json:"sort"`
	Limit            int      `json:"limit"`
	Offset           int      `json:"offset"`
}

// SearchItemCardsRow represents a lightweight item card with a total count.
type SearchItemCardsRow struct {
	ItemID          uuid.UUID          `json:"item_id"`
	OwnerID         uuid.UUID          `json:"owner_id"`
	AddressID       uuid.UUID          `json:"address_id"`
	Category        CategoryEnum       `json:"category"`
	Title           string             `json:"title"`
	ItemStatus      ItemStatus         `json:"item_status"`
	PricePerDay     pgtype.Numeric     `json:"price_per_day"`
	IsAvailable     bool               `json:"is_available"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	City            string             `json:"city"`
	PrimaryImageURL string             `json:"primary_image_url"`
	OwnerFirstName  string             `json:"owner_first_name"`
	OwnerLastName   string             `json:"owner_last_name"`
	OwnerAvatarURL  string             `json:"owner_avatar_url"`
	TotalCount      int64              `json:"total_count"`
}

const countItemCardsByCategory = `
SELECT
    i.category,
    COUNT(*) AS total_count
FROM item i
JOIN address a ON a.address_id = i.address_id
WHERE ($1 = false OR i.is_available = true)
  AND (
    $2 = ''
    OR i.title ILIKE '%' || $2 || '%'
    OR COALESCE(i.description, '') ILIKE '%' || $2 || '%'
  )
  AND ($3 = '' OR a.city ILIKE $3)
  AND ($4 = '' OR i.item_condition::text = $4)
  AND ($5::numeric IS NULL OR i.price_per_day >= $5::numeric)
  AND ($6::numeric IS NULL OR i.price_per_day <= $6::numeric)
GROUP BY i.category
`

const countItemCardsByCity = `
SELECT
    a.city,
    COUNT(*) AS total_count
FROM item i
JOIN address a ON a.address_id = i.address_id
WHERE ($1 = false OR i.is_available = true)
  AND (
    $2 = ''
    OR i.title ILIKE '%' || $2 || '%'
    OR COALESCE(i.description, '') ILIKE '%' || $2 || '%'
  )
  AND ($3 = '' OR i.category::text = $3)
  AND ($4 = '' OR i.item_condition::text = $4)
  AND ($5::numeric IS NULL OR i.price_per_day >= $5::numeric)
  AND ($6::numeric IS NULL OR i.price_per_day <= $6::numeric)
GROUP BY a.city
ORDER BY total_count DESC, a.city
`

const countItemCardsByCondition = `
SELECT
    i.item_condition,
    COUNT(*) AS total_count
FROM item i
JOIN address a ON a.address_id = i.address_id
WHERE ($1 = false OR i.is_available = true)
  AND (
    $2 = ''
    OR i.title ILIKE '%' || $2 || '%'
    OR COALESCE(i.description, '') ILIKE '%' || $2 || '%'
  )
  AND ($3 = '' OR i.category::text = $3)
  AND ($4 = '' OR a.city ILIKE $4)
  AND ($5::numeric IS NULL OR i.price_per_day >= $5::numeric)
  AND ($6::numeric IS NULL OR i.price_per_day <= $6::numeric)
GROUP BY i.item_condition
`

// CountItemCardsByCategoryParams defines filters for category aggregation.
type CountItemCardsByCategoryParams struct {
	RequireAvailable bool     `json:"require_available"`
	Query            string   `json:"query"`
	City             string   `json:"city"`
	Condition        string   `json:"condition"`
	MinPrice         *float64 `json:"min_price"`
	MaxPrice         *float64 `json:"max_price"`
}

// CountItemCardsByCategoryRow aggregates item counts by category.
type CountItemCardsByCategoryRow struct {
	Category   CategoryEnum `json:"category"`
	TotalCount int64        `json:"total_count"`
}

// CountItemCardsByCityParams defines filters for city aggregation.
type CountItemCardsByCityParams struct {
	RequireAvailable bool     `json:"require_available"`
	Query            string   `json:"query"`
	Category         string   `json:"category"`
	Condition        string   `json:"condition"`
	MinPrice         *float64 `json:"min_price"`
	MaxPrice         *float64 `json:"max_price"`
}

// CountItemCardsByCityRow aggregates item counts by city.
type CountItemCardsByCityRow struct {
	City       string `json:"city"`
	TotalCount int64  `json:"total_count"`
}

// CountItemCardsByConditionParams defines filters for condition aggregation.
type CountItemCardsByConditionParams struct {
	RequireAvailable bool     `json:"require_available"`
	Query            string   `json:"query"`
	Category         string   `json:"category"`
	City             string   `json:"city"`
	MinPrice         *float64 `json:"min_price"`
	MaxPrice         *float64 `json:"max_price"`
}

// CountItemCardsByConditionRow aggregates item counts by condition.
type CountItemCardsByConditionRow struct {
	Condition  ItemCondition `json:"condition"`
	TotalCount int64         `json:"total_count"`
}

// SearchItemCards returns a paginated list of item cards matching filters.
func (q *Queries) SearchItemCards(ctx context.Context, arg SearchItemCardsParams) ([]SearchItemCardsRow, error) {
	rows, err := q.db.Query(
		ctx,
		searchItemCards,
		arg.RequireAvailable,
		arg.Query,
		arg.Category,
		arg.City,
		arg.Condition,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Sort,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []SearchItemCardsRow
	for rows.Next() {
		var i SearchItemCardsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.OwnerID,
			&i.AddressID,
			&i.Category,
			&i.Title,
			&i.ItemStatus,
			&i.PricePerDay,
			&i.IsAvailable,
			&i.PublishedAt,
			&i.City,
			&i.PrimaryImageURL,
			&i.OwnerFirstName,
			&i.OwnerLastName,
			&i.OwnerAvatarURL,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

func countItemCardsRows[T any](ctx context.Context, db DBTX, sql string, scan func(pgx.Rows) (T, error), args ...any) ([]T, error) {
	rows, err := db.Query(ctx, sql, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var counts []T
	for rows.Next() {
		row, err := scan(rows)
		if err != nil {
			return nil, err
		}
		counts = append(counts, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return counts, nil
}

// CountItemCardsByCategory returns item counts grouped by category.
func (q *Queries) CountItemCardsByCategory(ctx context.Context, arg CountItemCardsByCategoryParams) ([]CountItemCardsByCategoryRow, error) {
	return countItemCardsRows(
		ctx,
		q.db,
		countItemCardsByCategory,
		func(rows pgx.Rows) (CountItemCardsByCategoryRow, error) {
			var row CountItemCardsByCategoryRow
			if err := rows.Scan(&row.Category, &row.TotalCount); err != nil {
				return row, err
			}
			return row, nil
		},
		arg.RequireAvailable,
		arg.Query,
		arg.City,
		arg.Condition,
		arg.MinPrice,
		arg.MaxPrice,
	)
}

// CountItemCardsByCity returns item counts grouped by city.
func (q *Queries) CountItemCardsByCity(ctx context.Context, arg CountItemCardsByCityParams) ([]CountItemCardsByCityRow, error) {
	return countItemCardsRows(
		ctx,
		q.db,
		countItemCardsByCity,
		func(rows pgx.Rows) (CountItemCardsByCityRow, error) {
			var row CountItemCardsByCityRow
			if err := rows.Scan(&row.City, &row.TotalCount); err != nil {
				return row, err
			}
			return row, nil
		},
		arg.RequireAvailable,
		arg.Query,
		arg.Category,
		arg.Condition,
		arg.MinPrice,
		arg.MaxPrice,
	)
}

// CountItemCardsByCondition returns item counts grouped by condition.
func (q *Queries) CountItemCardsByCondition(ctx context.Context, arg CountItemCardsByConditionParams) ([]CountItemCardsByConditionRow, error) {
	return countItemCardsRows(
		ctx,
		q.db,
		countItemCardsByCondition,
		func(rows pgx.Rows) (CountItemCardsByConditionRow, error) {
			var row CountItemCardsByConditionRow
			if err := rows.Scan(&row.Condition, &row.TotalCount); err != nil {
				return row, err
			}
			return row, nil
		},
		arg.RequireAvailable,
		arg.Query,
		arg.Category,
		arg.City,
		arg.MinPrice,
		arg.MaxPrice,
	)
}
