// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_image.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const createItemImage = `-- name: CreateItemImage :one

INSERT INTO item_image (item_id, image_url, display_order)
VALUES ($1, $2, $3)
RETURNING image_id, item_id, image_url, display_order
`

type CreateItemImageParams struct {
	ItemID       uuid.UUID `json:"item_id"`
	ImageUrl     string    `json:"image_url"`
	DisplayOrder int32     `json:"display_order"`
}

// ============================================
// CREATE
// ============================================
func (q *Queries) CreateItemImage(ctx context.Context, arg CreateItemImageParams) (ItemImage, error) {
	row := q.db.QueryRow(ctx, createItemImage, arg.ItemID, arg.ImageUrl, arg.DisplayOrder)
	var i ItemImage
	err := row.Scan(
		&i.ImageID,
		&i.ItemID,
		&i.ImageUrl,
		&i.DisplayOrder,
	)
	return i, err
}

const deleteItemImages = `-- name: DeleteItemImages :exec

DELETE FROM item_image WHERE item_id = $1
`

// ============================================
// DELETE
// ============================================
func (q *Queries) DeleteItemImages(ctx context.Context, itemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteItemImages, itemID)
	return err
}

const getItemImages = `-- name: GetItemImages :many

SELECT image_id, item_id, image_url, display_order
FROM item_image
WHERE item_id = $1
ORDER BY display_order ASC
`

// ============================================
// READ
// ============================================
func (q *Queries) GetItemImages(ctx context.Context, itemID uuid.UUID) ([]ItemImage, error) {
	rows, err := q.db.Query(ctx, getItemImages, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemImage
	for rows.Next() {
		var i ItemImage
		if err := rows.Scan(
			&i.ImageID,
			&i.ItemID,
			&i.ImageUrl,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
