// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAvailableItems = `-- name: CountAvailableItems :one
SELECT COUNT(*) FROM item WHERE is_available = true
`

func (q *Queries) CountAvailableItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAvailableItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countItems = `-- name: CountItems :one
SELECT COUNT(*) FROM item
`

func (q *Queries) CountItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countItemsByOwner = `-- name: CountItemsByOwner :one
SELECT COUNT(*) FROM item WHERE owner_id = $1
`

func (q *Queries) CountItemsByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countItemsByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :one

INSERT INTO item (
    owner_id,
    address_id,
    category,
    title,
    description,
    usage_rules,
    item_condition,
    price_per_day,
    deposit,
    min_days,
    max_days
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING
    item_id,
    owner_id,
    address_id,
    category,
    title,
    description,
    usage_rules,
    item_condition,
    item_status,
    price_per_day,
    deposit,
    min_days,
    max_days,
    is_available,
    published_at
`

type CreateItemParams struct {
	OwnerID     uuid.UUID      `json:"owner_id"`
	AddressID   uuid.UUID      `json:"address_id"`
	Category    CategoryEnum   `json:"category"`
	Title       string         `json:"title"`
	Description pgtype.Text    `json:"description"`
	UsageRules  pgtype.Text    `json:"usage_rules"`
	Condition   ItemCondition  `json:"condition"`
	PricePerDay pgtype.Numeric `json:"price_per_day"`
	Deposit     pgtype.Numeric `json:"deposit"`
	MinDays     int32          `json:"min_days"`
	MaxDays     pgtype.Int4    `json:"max_days"`
}

// ============================================
// CREATE
// ============================================
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.OwnerID,
		arg.AddressID,
		arg.Category,
		arg.Title,
		arg.Description,
		arg.UsageRules,
		arg.Condition,
		arg.PricePerDay,
		arg.Deposit,
		arg.MinDays,
		arg.MaxDays,
	)
	var i Item
	err := row.Scan(
		&i.ItemID,
		&i.OwnerID,
		&i.AddressID,
		&i.Category,
		&i.Title,
		&i.Description,
		&i.UsageRules,
		&i.Condition,
		&i.ItemStatus,
		&i.PricePerDay,
		&i.Deposit,
		&i.MinDays,
		&i.MaxDays,
		&i.IsAvailable,
		&i.PublishedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec

DELETE FROM item
WHERE item_id = $1
`

// ============================================
// DELETE
// ============================================
func (q *Queries) DeleteItem(ctx context.Context, itemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteItem, itemID)
	return err
}

const existsItemByID = `-- name: ExistsItemByID :one
SELECT EXISTS (
    SELECT 1 FROM item WHERE item_id = $1
) AS item_exists
`

func (q *Queries) ExistsItemByID(ctx context.Context, itemID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsItemByID, itemID)
	var item_exists bool
	err := row.Scan(&item_exists)
	return item_exists, err
}

const getItemByID = `-- name: GetItemByID :one

SELECT
    item_id,
    owner_id,
    address_id,
    category,
    title,
    description,
    usage_rules,
    item_condition,
    item_status,
    price_per_day,
    deposit,
    min_days,
    max_days,
    is_available,
    published_at
FROM item
WHERE item_id = $1
LIMIT 1
`

// ============================================
// READ
// ============================================
func (q *Queries) GetItemByID(ctx context.Context, itemID uuid.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByID, itemID)
	var i Item
	err := row.Scan(
		&i.ItemID,
		&i.OwnerID,
		&i.AddressID,
		&i.Category,
		&i.Title,
		&i.Description,
		&i.UsageRules,
		&i.Condition,
		&i.ItemStatus,
		&i.PricePerDay,
		&i.Deposit,
		&i.MinDays,
		&i.MaxDays,
		&i.IsAvailable,
		&i.PublishedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT
    item_id,
    owner_id,
    address_id,
    category,
    title,
    description,
    usage_rules,
    item_status,
    price_per_day,
    deposit,
    min_days,
    max_days,
    is_available,
    published_at
FROM item
WHERE is_available = true
ORDER BY published_at DESC
LIMIT $1 OFFSET $2
`

type ListItemsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ItemID,
			&i.OwnerID,
			&i.AddressID,
			&i.Category,
			&i.Title,
			&i.Description,
			&i.UsageRules,
			&i.ItemStatus,
			&i.PricePerDay,
			&i.Deposit,
			&i.MinDays,
			&i.MaxDays,
			&i.IsAvailable,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByCategory = `-- name: ListItemsByCategory :many
SELECT
    item_id,
    owner_id,
    address_id,
    category,
    title,
    description,
    usage_rules,
    item_status,
    price_per_day,
    deposit,
    min_days,
    max_days,
    is_available,
    published_at
FROM item
WHERE category = $1
  AND is_available = true
ORDER BY published_at DESC
LIMIT $2 OFFSET $3
`

type ListItemsByCategoryParams struct {
	Category CategoryEnum `json:"category"`
	Limit    int32        `json:"limit"`
	Offset   int32        `json:"offset"`
}

func (q *Queries) ListItemsByCategory(ctx context.Context, arg ListItemsByCategoryParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsByCategory, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ItemID,
			&i.OwnerID,
			&i.AddressID,
			&i.Category,
			&i.Title,
			&i.Description,
			&i.UsageRules,
			&i.ItemStatus,
			&i.PricePerDay,
			&i.Deposit,
			&i.MinDays,
			&i.MaxDays,
			&i.IsAvailable,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByOwner = `-- name: ListItemsByOwner :many
SELECT
    item_id,
    owner_id,
    address_id,
    category,
    title,
    description,
    usage_rules,
    item_status,
    price_per_day,
    deposit,
    min_days,
    max_days,
    is_available,
    published_at
FROM item
WHERE owner_id = $1
ORDER BY published_at DESC
LIMIT $2 OFFSET $3
`

type ListItemsByOwnerParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListItemsByOwner(ctx context.Context, arg ListItemsByOwnerParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsByOwner, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ItemID,
			&i.OwnerID,
			&i.AddressID,
			&i.Category,
			&i.Title,
			&i.Description,
			&i.UsageRules,
			&i.ItemStatus,
			&i.PricePerDay,
			&i.Deposit,
			&i.MinDays,
			&i.MaxDays,
			&i.IsAvailable,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItems = `-- name: SearchItems :many
SELECT
    item_id,
    owner_id,
    address_id,
    category,
    title,
    description,
    usage_rules,
    item_status,
    price_per_day,
    deposit,
    min_days,
    max_days,
    is_available,
    published_at
FROM item
WHERE (title ILIKE $1 OR description ILIKE $1)
  AND is_available = true
ORDER BY published_at DESC
LIMIT $2 OFFSET $3
`

type SearchItemsParams struct {
	Title  string `json:"title"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchItems(ctx context.Context, arg SearchItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, searchItems, arg.Title, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ItemID,
			&i.OwnerID,
			&i.AddressID,
			&i.Category,
			&i.Title,
			&i.Description,
			&i.UsageRules,
			&i.ItemStatus,
			&i.PricePerDay,
			&i.Deposit,
			&i.MinDays,
			&i.MaxDays,
			&i.IsAvailable,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteItem = `-- name: SoftDeleteItem :exec
UPDATE item
SET is_available = false,
    item_status  = 'retired'
WHERE item_id = $1
`

func (q *Queries) SoftDeleteItem(ctx context.Context, itemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteItem, itemID)
	return err
}

const updateItem = `-- name: UpdateItem :one

UPDATE item
SET
    title         = $2,
    description   = $3,
    usage_rules   = $4,
    category      = $5,
    price_per_day = $6,
    deposit       = $7,
    min_days      = $8,
    max_days      = $9
WHERE item_id = $1
RETURNING
    item_id,
    owner_id,
    address_id,
    category,
    title,
    description,
    usage_rules,
    item_status,
    price_per_day,
    deposit,
    min_days,
    max_days,
    is_available,
    published_at
`

type UpdateItemParams struct {
	ItemID      uuid.UUID      `json:"item_id"`
	Title       string         `json:"title"`
	Description pgtype.Text    `json:"description"`
	UsageRules  pgtype.Text    `json:"usage_rules"`
	Category    CategoryEnum   `json:"category"`
	PricePerDay pgtype.Numeric `json:"price_per_day"`
	Deposit     pgtype.Numeric `json:"deposit"`
	MinDays     int32          `json:"min_days"`
	MaxDays     pgtype.Int4    `json:"max_days"`
}

// ============================================
// UPDATE
// ============================================
func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.ItemID,
		arg.Title,
		arg.Description,
		arg.UsageRules,
		arg.Category,
		arg.PricePerDay,
		arg.Deposit,
		arg.MinDays,
		arg.MaxDays,
	)
	var i Item
	err := row.Scan(
		&i.ItemID,
		&i.OwnerID,
		&i.AddressID,
		&i.Category,
		&i.Title,
		&i.Description,
		&i.UsageRules,
		&i.ItemStatus,
		&i.PricePerDay,
		&i.Deposit,
		&i.MinDays,
		&i.MaxDays,
		&i.IsAvailable,
		&i.PublishedAt,
	)
	return i, err
}

const updateItemAvailability = `-- name: UpdateItemAvailability :exec
UPDATE item
SET is_available = $2
WHERE item_id = $1
`

type UpdateItemAvailabilityParams struct {
	ItemID      uuid.UUID `json:"item_id"`
	IsAvailable bool      `json:"is_available"`
}

func (q *Queries) UpdateItemAvailability(ctx context.Context, arg UpdateItemAvailabilityParams) error {
	_, err := q.db.Exec(ctx, updateItemAvailability, arg.ItemID, arg.IsAvailable)
	return err
}

const updateItemStatus = `-- name: UpdateItemStatus :one
UPDATE item
SET item_status = $2
WHERE item_id = $1
RETURNING item_id, item_status
`

type UpdateItemStatusParams struct {
	ItemID     uuid.UUID  `json:"item_id"`
	ItemStatus ItemStatus `json:"item_status"`
}

type UpdateItemStatusRow struct {
	ItemID     uuid.UUID  `json:"item_id"`
	ItemStatus ItemStatus `json:"item_status"`
}

func (q *Queries) UpdateItemStatus(ctx context.Context, arg UpdateItemStatusParams) (UpdateItemStatusRow, error) {
	row := q.db.QueryRow(ctx, updateItemStatus, arg.ItemID, arg.ItemStatus)
	var i UpdateItemStatusRow
	err := row.Scan(&i.ItemID, &i.ItemStatus)
	return i, err
}
