// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCustomers(ctx context.Context) (int64, error)
	// ============================================
	// CREATE
	// ============================================
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (CreateCustomerRow, error)
	// ============================================
	// DELETE
	// ============================================
	DeleteCustomer(ctx context.Context, customerID uuid.UUID) error
	ExistsCustomerByEmail(ctx context.Context, email string) (bool, error)
	GetCustomerByEmail(ctx context.Context, email string) (Customer, error)
	// ============================================
	// READ
	// ============================================
	GetCustomerByID(ctx context.Context, customerID uuid.UUID) (GetCustomerByIDRow, error)
	GetCustomerByStripeID(ctx context.Context, stripeCustomerID pgtype.Text) (GetCustomerByStripeIDRow, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error)
	ListCustomersByStatus(ctx context.Context, arg ListCustomersByStatusParams) ([]ListCustomersByStatusRow, error)
	SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]SearchCustomersRow, error)
	SoftDeleteCustomer(ctx context.Context, customerID uuid.UUID) error
	UpdateCustomerAvatar(ctx context.Context, arg UpdateCustomerAvatarParams) error
	UpdateCustomerEmail(ctx context.Context, arg UpdateCustomerEmailParams) (UpdateCustomerEmailRow, error)
	UpdateCustomerPassword(ctx context.Context, arg UpdateCustomerPasswordParams) error
	// ============================================
	// UPDATE
	// ============================================
	UpdateCustomerProfile(ctx context.Context, arg UpdateCustomerProfileParams) (UpdateCustomerProfileRow, error)
	UpdateCustomerRole(ctx context.Context, arg UpdateCustomerRoleParams) (UpdateCustomerRoleRow, error)
	UpdateCustomerStatus(ctx context.Context, arg UpdateCustomerStatusParams) (UpdateCustomerStatusRow, error)
	UpdateCustomerStripeID(ctx context.Context, arg UpdateCustomerStripeIDParams) error
}

var _ Querier = (*Queries)(nil)
