// Package service contains business logic for the API.
package service

import (
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/isw2-unileon/MeRenta/backend/internal/model"
	"github.com/isw2-unileon/MeRenta/backend/internal/sqlcdb"
)

var (
	// ErrInvalidCategory indicates the category value is not recognised.
	ErrInvalidCategory = errors.New("invalid category")
	// ErrAddressNotFound indicates the provided address_id does not exist.
	ErrAddressNotFound = errors.New("address not found")
)

// itemQuerier is the minimal DB interface needed by ItemService.
// It allows swapping the implementation in tests without depending on the
// full sqlcdb.Querier interface (which is regenerated by sqlc).
type itemQuerier interface {
	CreateItem(ctx context.Context, arg sqlcdb.CreateItemParams) (sqlcdb.Item, error)
	GetItemByID(ctx context.Context, itemID uuid.UUID) (sqlcdb.Item, error)
}

// ItemService handles item listing use cases.
type ItemService struct {
	q itemQuerier
}

// NewItemService creates an ItemService with its dependencies.
func NewItemService(q itemQuerier) *ItemService {
	return &ItemService{q: q}
}

// CreateItem inserts a new item listing owned by the authenticated customer.
func (s *ItemService) CreateItem(ctx context.Context, ownerID uuid.UUID, req model.CreateItemRequest) (*model.ItemResponse, error) {
	if !isValidCategory(req.Category) {
		return nil, ErrInvalidCategory
	}

	addressID, err := uuid.Parse(req.AddressID)
	if err != nil {
		return nil, fmt.Errorf("parsing address_id: %w", err)
	}

	pricePerDay, err := float64ToNumeric(req.PricePerDay)
	if err != nil {
		return nil, fmt.Errorf("invalid price_per_day: %w", err)
	}

	deposit, err := optionalFloat64ToNumeric(req.Deposit)
	if err != nil {
		return nil, fmt.Errorf("invalid deposit: %w", err)
	}

	item, err := s.q.CreateItem(ctx, sqlcdb.CreateItemParams{
		OwnerID:     ownerID,
		AddressID:   addressID,
		Category:    sqlcdb.CategoryEnum(req.Category),
		Title:       req.Title,
		Description: pgtype.Text{String: req.Description, Valid: req.Description != ""},
		Brand:       pgtype.Text{String: req.Brand, Valid: req.Brand != ""},
		Model:       pgtype.Text{String: req.Model, Valid: req.Model != ""},
		PricePerDay: pricePerDay,
		Deposit:     deposit,
	})
	if err != nil {
		if isForeignKeyViolation(err) {
			return nil, ErrAddressNotFound
		}
		return nil, err
	}

	return toItemResponse(item)
}

// GetItem fetches a single item by its UUID.
// Returns ErrItemNotFound when the item does not exist.
func (s *ItemService) GetItem(ctx context.Context, itemID uuid.UUID) (*model.ItemResponse, error) {
	item, err := s.q.GetItemByID(ctx, itemID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrItemNotFound
		}
		return nil, err
	}

	return toItemResponse(item)
}

// toItemResponse maps a sqlcdb.Item to the API response model.
func toItemResponse(item sqlcdb.Item) (*model.ItemResponse, error) {
	pricePerDay, err := numericToFloat64(item.PricePerDay)
	if err != nil {
		return nil, fmt.Errorf("converting price_per_day: %w", err)
	}

	var deposit *float64
	if item.Deposit.Valid {
		d, err := numericToFloat64(item.Deposit)
		if err != nil {
			return nil, fmt.Errorf("converting deposit: %w", err)
		}
		deposit = &d
	}

	return &model.ItemResponse{
		ItemID:      item.ItemID.String(),
		OwnerID:     item.OwnerID.String(),
		AddressID:   item.AddressID.String(),
		Category:    string(item.Category),
		Title:       item.Title,
		Description: item.Description.String,
		Brand:       item.Brand.String,
		Model:       item.Model.String,
		ItemStatus:  string(item.ItemStatus),
		PricePerDay: pricePerDay,
		Deposit:     deposit,
		IsAvailable: item.IsAvailable,
		PublishedAt: item.PublishedAt.Time,
	}, nil
}

// isValidCategory checks whether c is one of the allowed category values.
func isValidCategory(c string) bool {
	switch sqlcdb.CategoryEnum(c) {
	case sqlcdb.CategoryEnumTools,
		sqlcdb.CategoryEnumElectronics,
		sqlcdb.CategoryEnumSports,
		sqlcdb.CategoryEnumVehicles,
		sqlcdb.CategoryEnumHome,
		sqlcdb.CategoryEnumClothing,
		sqlcdb.CategoryEnumMusic,
		sqlcdb.CategoryEnumGarden,
		sqlcdb.CategoryEnumLeisure,
		sqlcdb.CategoryEnumOther:
		return true
	default:
		return false
	}
}

// float64ToNumeric converts a float64 to a valid pgtype.Numeric with 2 decimal places.
func float64ToNumeric(v float64) (pgtype.Numeric, error) {
	var n pgtype.Numeric
	err := n.Scan(strconv.FormatFloat(v, 'f', 2, 64))
	return n, err
}

// optionalFloat64ToNumeric returns an invalid (NULL) Numeric when v is nil.
func optionalFloat64ToNumeric(v *float64) (pgtype.Numeric, error) {
	if v == nil {
		return pgtype.Numeric{}, nil
	}
	return float64ToNumeric(*v)
}

// numericToFloat64 extracts the float64 value from a pgtype.Numeric.
func numericToFloat64(n pgtype.Numeric) (float64, error) {
	f, err := n.Float64Value()
	if err != nil {
		return 0, err
	}
	return f.Float64, nil
}

// isForeignKeyViolation reports whether err is a PostgreSQL FK violation (23503).
func isForeignKeyViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23503"
}
