// Package service contains business logic for the API.
package service

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/isw2-unileon/MeRenta/backend/internal/model"
	"github.com/isw2-unileon/MeRenta/backend/internal/sqlcdb"
)

var (
	// ErrInvalidCategory indicates the category value is not recognised.
	ErrInvalidCategory = errors.New("invalid category")
	// ErrAddressNotFound indicates the provided address_id does not exist.
	ErrAddressNotFound = errors.New("address not found")
	// ErrInvalidRentalPeriod indicates an invalid min/max rental-day range.
	ErrInvalidRentalPeriod = errors.New("invalid rental period")
	// ErrInvalidCondition indicates the condition value is not recognised.
	ErrInvalidCondition = errors.New("invalid condition")
	// ErrInvalidItemStatus indicates the item status cannot be set through editing.
	ErrInvalidItemStatus = errors.New("invalid item status")
)

// itemQuerier is the minimal DB interface needed by ItemService.
// It allows swapping the implementation in tests without depending on the
// full sqlcdb.Querier interface (which is regenerated by sqlc).
type itemQuerier interface {
	CreateItem(ctx context.Context, arg sqlcdb.CreateItemParams) (sqlcdb.CreateItemRow, error)
	GetItemByID(ctx context.Context, itemID uuid.UUID) (sqlcdb.GetItemByIDRow, error)
	ExistsItemByID(ctx context.Context, itemID uuid.UUID) (bool, error)
	UpdateItemForOwner(ctx context.Context, arg sqlcdb.UpdateItemForOwnerParams) (sqlcdb.GetItemByIDRow, error)
	DeleteItemForOwner(ctx context.Context, itemID, ownerID uuid.UUID) error
	ListOwnerItemCards(ctx context.Context, arg sqlcdb.ListOwnerItemCardsParams) ([]sqlcdb.SearchItemCardsRow, error)
	ListOwnerItemCardsWithoutImages(ctx context.Context, arg sqlcdb.ListOwnerItemCardsParams) ([]sqlcdb.SearchItemCardsRow, error)
	CountItemsByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error)
	SearchItemCards(ctx context.Context, arg sqlcdb.SearchItemCardsParams) ([]sqlcdb.SearchItemCardsRow, error)
	CountItemCardsByCategory(ctx context.Context, arg sqlcdb.CountItemCardsByCategoryParams) ([]sqlcdb.CountItemCardsByCategoryRow, error)
	CountItemCardsByCity(ctx context.Context, arg sqlcdb.CountItemCardsByCityParams) ([]sqlcdb.CountItemCardsByCityRow, error)
	CountItemCardsByCondition(ctx context.Context, arg sqlcdb.CountItemCardsByConditionParams) ([]sqlcdb.CountItemCardsByConditionRow, error)
}

type updateItemValues struct {
	addressID   uuid.UUID
	pricePerDay pgtype.Numeric
	deposit     pgtype.Numeric
	minDays     int32
	maxDays     pgtype.Int4
}

// ItemService handles item listing use cases.
type ItemService struct {
	q itemQuerier
}

// NewItemService creates an ItemService with its dependencies.
func NewItemService(q itemQuerier) *ItemService {
	return &ItemService{q: q}
}

// CreateItem inserts a new item listing owned by the authenticated customer.
func (s *ItemService) CreateItem(ctx context.Context, ownerID uuid.UUID, req model.CreateItemRequest) (*model.ItemResponse, error) {
	if !isValidCategory(req.Category) {
		return nil, ErrInvalidCategory
	}
	if !isValidCondition(req.Condition) {
		return nil, ErrInvalidCondition
	}

	minDays := req.MinDays
	if minDays == 0 {
		minDays = 1
	}

	if req.MaxDays != nil && *req.MaxDays < minDays {
		return nil, ErrInvalidRentalPeriod
	}

	addressID, err := uuid.Parse(req.AddressID)
	if err != nil {
		return nil, fmt.Errorf("parsing address_id: %w", err)
	}

	pricePerDay, err := float64ToNumeric(req.PricePerDay)
	if err != nil {
		return nil, fmt.Errorf("invalid price_per_day: %w", err)
	}

	deposit, err := optionalFloat64ToNumeric(req.Deposit)
	if err != nil {
		return nil, fmt.Errorf("invalid deposit: %w", err)
	}

	maxDays, err := optionalIntToInt4(req.MaxDays)
	if err != nil {
		return nil, fmt.Errorf("invalid max_days: %w", err)
	}

	item, err := s.q.CreateItem(ctx, sqlcdb.CreateItemParams{
		OwnerID:       ownerID,
		AddressID:     addressID,
		Category:      sqlcdb.CategoryEnum(req.Category),
		Title:         req.Title,
		Description:   pgtype.Text{String: req.Description, Valid: req.Description != ""},
		UsageRules:    pgtype.Text{String: req.UsageRules, Valid: req.UsageRules != ""},
		ItemCondition: sqlcdb.ItemCondition(req.Condition),
		PricePerDay:   pricePerDay,
		Deposit:       deposit,
		MinDays:       int32(minDays),
		MaxDays:       maxDays,
	})
	if err != nil {
		if isForeignKeyViolation(err) {
			return nil, ErrAddressNotFound
		}
		if isInvalidTextRepresentation(err) {
			return nil, ErrInvalidCategory
		}
		return nil, err
	}

	return toItemResponseFromCreateRow(item)
}

// UpdateItem updates an item listing owned by the authenticated customer.
func (s *ItemService) UpdateItem(
	ctx context.Context,
	ownerID uuid.UUID,
	itemID uuid.UUID,
	req model.UpdateItemRequest,
) (*model.ItemResponse, error) {
	values, err := prepareUpdateItemValues(req)
	if err != nil {
		return nil, err
	}

	item, err := s.q.UpdateItemForOwner(ctx, sqlcdb.UpdateItemForOwnerParams{
		ItemID:        itemID,
		OwnerID:       ownerID,
		AddressID:     values.addressID,
		Category:      sqlcdb.CategoryEnum(req.Category),
		Title:         req.Title,
		Description:   pgtype.Text{String: req.Description, Valid: req.Description != ""},
		UsageRules:    pgtype.Text{String: req.UsageRules, Valid: req.UsageRules != ""},
		ItemCondition: sqlcdb.ItemCondition(req.Condition),
		PricePerDay:   values.pricePerDay,
		Deposit:       values.deposit,
		MinDays:       values.minDays,
		MaxDays:       values.maxDays,
		IsAvailable:   req.IsAvailable != nil && *req.IsAvailable,
		ItemStatus:    sqlcdb.ItemStatus(req.ItemStatus),
	})
	if err != nil {
		return nil, s.mapUpdateItemError(ctx, itemID, err)
	}

	return toItemResponse(item)
}

// DeleteItem permanently deletes an item listing owned by the authenticated customer.
func (s *ItemService) DeleteItem(ctx context.Context, ownerID uuid.UUID, itemID uuid.UUID) error {
	if err := s.q.DeleteItemForOwner(ctx, itemID, ownerID); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			exists, existsErr := s.q.ExistsItemByID(ctx, itemID)
			if existsErr != nil {
				return existsErr
			}
			if exists {
				return ErrForbidden
			}
			return ErrItemNotFound
		}
		return err
	}

	return nil
}

func prepareUpdateItemValues(req model.UpdateItemRequest) (updateItemValues, error) {
	if !isValidCategory(req.Category) {
		return updateItemValues{}, ErrInvalidCategory
	}
	if !isValidCondition(req.Condition) {
		return updateItemValues{}, ErrInvalidCondition
	}
	if !isValidEditableStatus(req.ItemStatus) {
		return updateItemValues{}, ErrInvalidItemStatus
	}

	minDays := req.MinDays
	if minDays == 0 {
		minDays = 1
	}
	if req.MaxDays != nil && *req.MaxDays < minDays {
		return updateItemValues{}, ErrInvalidRentalPeriod
	}
	minDaysInt32, err := intToInt32(minDays)
	if err != nil {
		return updateItemValues{}, fmt.Errorf("invalid min_days: %w", err)
	}

	addressID, err := uuid.Parse(req.AddressID)
	if err != nil {
		return updateItemValues{}, fmt.Errorf("parsing address_id: %w", err)
	}

	pricePerDay, err := float64ToNumeric(req.PricePerDay)
	if err != nil {
		return updateItemValues{}, fmt.Errorf("invalid price_per_day: %w", err)
	}

	deposit, err := optionalFloat64ToNumeric(req.Deposit)
	if err != nil {
		return updateItemValues{}, fmt.Errorf("invalid deposit: %w", err)
	}

	maxDays, err := optionalIntToInt4(req.MaxDays)
	if err != nil {
		return updateItemValues{}, fmt.Errorf("invalid max_days: %w", err)
	}

	return updateItemValues{
		addressID:   addressID,
		pricePerDay: pricePerDay,
		deposit:     deposit,
		minDays:     minDaysInt32,
		maxDays:     maxDays,
	}, nil
}

func (s *ItemService) mapUpdateItemError(ctx context.Context, itemID uuid.UUID, err error) error {
	if errors.Is(err, pgx.ErrNoRows) {
		exists, existsErr := s.q.ExistsItemByID(ctx, itemID)
		if existsErr != nil {
			return existsErr
		}
		if exists {
			return ErrForbidden
		}
		return ErrItemNotFound
	}
	if isForeignKeyViolation(err) {
		return ErrAddressNotFound
	}
	if isInvalidTextRepresentation(err) {
		return ErrInvalidCategory
	}
	return err
}

// GetItem fetches a single item by its UUID.
// Returns ErrItemNotFound when the item does not exist.
func (s *ItemService) GetItem(ctx context.Context, itemID uuid.UUID) (*model.ItemResponse, error) {
	item, err := s.q.GetItemByID(ctx, itemID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrItemNotFound
		}
		return nil, err
	}

	return toItemResponse(item)
}

// ListOwnerItems returns paginated item cards owned by the authenticated customer.
func (s *ItemService) ListOwnerItems(ctx context.Context, ownerID uuid.UUID, page int, limit int) (*model.SearchItemsResponse, error) {
	offset := (page - 1) * limit

	params := sqlcdb.ListOwnerItemCardsParams{
		OwnerID: ownerID,
		Limit:   limit,
		Offset:  offset,
	}

	rows, err := s.q.ListOwnerItemCards(ctx, params)
	if err != nil && isUndefinedTableNamed(err, "item_image") {
		rows, err = s.q.ListOwnerItemCardsWithoutImages(ctx, params)
	}
	if err != nil {
		return nil, err
	}

	total, err := s.q.CountItemsByOwner(ctx, ownerID)
	if err != nil {
		return nil, err
	}

	items := make([]model.SearchItemResponse, 0, len(rows))
	for _, row := range rows {
		pricePerDay, err := numericToFloat64(row.PricePerDay)
		if err != nil {
			return nil, fmt.Errorf("converting price_per_day: %w", err)
		}

		items = append(items, model.SearchItemResponse{
			ItemID:          row.ItemID.String(),
			OwnerID:         row.OwnerID.String(),
			AddressID:       row.AddressID.String(),
			Category:        string(row.Category),
			Title:           row.Title,
			ItemStatus:      string(row.ItemStatus),
			PricePerDay:     pricePerDay,
			IsAvailable:     row.IsAvailable,
			PublishedAt:     row.PublishedAt.Time,
			City:            row.City,
			PostalCode:      row.PostalCode,
			PrimaryImageURL: row.PrimaryImageURL,
		})
	}

	return &model.SearchItemsResponse{
		Items:           items,
		Total:           total,
		Page:            page,
		Limit:           limit,
		CategoryCounts:  map[string]int64{},
		CityCounts:      map[string]int64{},
		ConditionCounts: map[string]int64{},
	}, nil
}

// SearchItems returns paginated item cards for the search page.
func (s *ItemService) SearchItems(ctx context.Context, params sqlcdb.SearchItemCardsParams, page int, limit int) (*model.SearchItemsResponse, error) {
	rows, err := s.q.SearchItemCards(ctx, params)
	if err != nil {
		return nil, err
	}

	countRows, err := s.q.CountItemCardsByCategory(ctx, sqlcdb.CountItemCardsByCategoryParams{
		RequireAvailable: params.RequireAvailable,
		Query:            params.Query,
		City:             params.City,
		Condition:        params.Condition,
		MinPrice:         params.MinPrice,
		MaxPrice:         params.MaxPrice,
	})
	if err != nil {
		return nil, err
	}

	cityRows, err := s.q.CountItemCardsByCity(ctx, sqlcdb.CountItemCardsByCityParams{
		RequireAvailable: params.RequireAvailable,
		Query:            params.Query,
		Category:         params.Category,
		Condition:        params.Condition,
		MinPrice:         params.MinPrice,
		MaxPrice:         params.MaxPrice,
	})
	if err != nil {
		return nil, err
	}

	conditionRows, err := s.q.CountItemCardsByCondition(ctx, sqlcdb.CountItemCardsByConditionParams{
		RequireAvailable: params.RequireAvailable,
		Query:            params.Query,
		Category:         params.Category,
		City:             params.City,
		MinPrice:         params.MinPrice,
		MaxPrice:         params.MaxPrice,
	})
	if err != nil {
		return nil, err
	}

	items := make([]model.SearchItemResponse, 0, len(rows))
	categoryCounts := make(map[string]int64, len(countRows))
	for _, row := range countRows {
		categoryCounts[string(row.Category)] = row.TotalCount
	}
	cityCounts := make(map[string]int64, len(cityRows))
	for _, row := range cityRows {
		cityCounts[row.City] = row.TotalCount
	}
	conditionCounts := make(map[string]int64, len(conditionRows))
	for _, row := range conditionRows {
		conditionCounts[string(row.Condition)] = row.TotalCount
	}

	var total int64
	for _, row := range rows {
		if total == 0 {
			total = row.TotalCount
		}

		pricePerDay, err := numericToFloat64(row.PricePerDay)
		if err != nil {
			return nil, fmt.Errorf("converting price_per_day: %w", err)
		}

		items = append(items, model.SearchItemResponse{
			ItemID:          row.ItemID.String(),
			OwnerID:         row.OwnerID.String(),
			AddressID:       row.AddressID.String(),
			Category:        string(row.Category),
			Title:           row.Title,
			ItemStatus:      string(row.ItemStatus),
			PricePerDay:     pricePerDay,
			IsAvailable:     row.IsAvailable,
			PublishedAt:     row.PublishedAt.Time,
			City:            row.City,
			PostalCode:      row.PostalCode,
			PrimaryImageURL: row.PrimaryImageURL,
			OwnerFirstName:  row.OwnerFirstName,
			OwnerLastName:   row.OwnerLastName,
			OwnerAvatarURL:  row.OwnerAvatarURL,
		})
	}

	return &model.SearchItemsResponse{
		Items:           items,
		Total:           total,
		Page:            page,
		Limit:           limit,
		CategoryCounts:  categoryCounts,
		CityCounts:      cityCounts,
		ConditionCounts: conditionCounts,
	}, nil
}

// toItemResponse maps a sqlcdb.GetItemByIDRow to the API response model.
func toItemResponse(item sqlcdb.GetItemByIDRow) (*model.ItemResponse, error) {
	pricePerDay, err := numericToFloat64(item.PricePerDay)
	if err != nil {
		return nil, fmt.Errorf("converting price_per_day: %w", err)
	}

	var deposit *float64
	if item.Deposit.Valid {
		d, err := numericToFloat64(item.Deposit)
		if err != nil {
			return nil, fmt.Errorf("converting deposit: %w", err)
		}
		deposit = &d
	}

	var maxDays *int32
	if item.MaxDays.Valid {
		maxDays = &item.MaxDays.Int32
	}

	return &model.ItemResponse{
		ItemID:      item.ItemID.String(),
		OwnerID:     item.OwnerID.String(),
		AddressID:   item.AddressID.String(),
		Category:    string(item.Category),
		Title:       item.Title,
		Description: item.Description.String,
		UsageRules:  item.UsageRules.String,
		Condition:   string(item.ItemCondition),
		ItemStatus:  string(item.ItemStatus),
		PricePerDay: pricePerDay,
		Deposit:     deposit,
		MinDays:     item.MinDays,
		MaxDays:     maxDays,
		IsAvailable: item.IsAvailable,
		PublishedAt: item.PublishedAt.Time,
		City:        item.City,
		Province:    item.Province,
		PostalCode:  item.PostalCode,
	}, nil
}

// toItemResponseFromCreateRow adapts a CreateItemRow (returned by INSERT) to the
// same API response as toItemResponse. CreateItemRow and GetItemByIDRow have
// identical underlying structure, so a direct type conversion is safe.
func toItemResponseFromCreateRow(r sqlcdb.CreateItemRow) (*model.ItemResponse, error) {
	return toItemResponse(sqlcdb.GetItemByIDRow{
		ItemID:        r.ItemID,
		OwnerID:       r.OwnerID,
		AddressID:     r.AddressID,
		Category:      r.Category,
		Title:         r.Title,
		Description:   r.Description,
		UsageRules:    r.UsageRules,
		ItemCondition: r.ItemCondition,
		ItemStatus:    r.ItemStatus,
		PricePerDay:   r.PricePerDay,
		Deposit:       r.Deposit,
		MinDays:       r.MinDays,
		MaxDays:       r.MaxDays,
		IsAvailable:   r.IsAvailable,
		PublishedAt:   r.PublishedAt,
	})
}

// isValidCategory checks whether c is one of the allowed category values.
func isValidCategory(c string) bool {
	switch sqlcdb.CategoryEnum(c) {
	case sqlcdb.CategoryEnumTools,
		sqlcdb.CategoryEnumElectronics,
		sqlcdb.CategoryEnumSports,
		sqlcdb.CategoryEnumVehicles,
		sqlcdb.CategoryEnumHome,
		sqlcdb.CategoryEnumGardening,
		sqlcdb.CategoryEnumClothing,
		sqlcdb.CategoryEnumMusic,
		sqlcdb.CategoryEnumPhotography,
		sqlcdb.CategoryEnumCamping,
		sqlcdb.CategoryEnumLeisure,
		sqlcdb.CategoryEnumOther:
		return true
	default:
		return false
	}
}

func isValidCondition(c string) bool {
	switch sqlcdb.ItemCondition(c) {
	case sqlcdb.ItemConditionNew,
		sqlcdb.ItemConditionLikeNew,
		sqlcdb.ItemConditionGood,
		sqlcdb.ItemConditionFair,
		sqlcdb.ItemConditionPoor:
		return true
	default:
		return false
	}
}

func isValidEditableStatus(status string) bool {
	switch status {
	case string(sqlcdb.ItemStatusAvailable), "withdrawn":
		return true
	default:
		return false
	}
}

// float64ToNumeric converts a float64 to a valid pgtype.Numeric with 2 decimal places.
func float64ToNumeric(v float64) (pgtype.Numeric, error) {
	var n pgtype.Numeric
	err := n.Scan(strconv.FormatFloat(v, 'f', 2, 64))
	return n, err
}

// optionalFloat64ToNumeric returns an invalid (NULL) Numeric when v is nil.
func optionalFloat64ToNumeric(v *float64) (pgtype.Numeric, error) {
	if v == nil {
		return pgtype.Numeric{}, nil
	}
	return float64ToNumeric(*v)
}

func optionalIntToInt4(v *int) (pgtype.Int4, error) {
	if v == nil {
		return pgtype.Int4{}, nil
	}
	value, err := intToInt32(*v)
	if err != nil {
		return pgtype.Int4{}, err
	}

	return pgtype.Int4{Int32: value, Valid: true}, nil
}

func intToInt32(value int) (int32, error) {
	const minInt32 = -2147483648
	const maxInt32 = 2147483647
	if value < minInt32 || value > maxInt32 {
		return 0, fmt.Errorf("value %d overflows int32", value)
	}

	return int32(value), nil
}

// numericToFloat64 extracts the float64 value from a pgtype.Numeric.
func numericToFloat64(n pgtype.Numeric) (float64, error) {
	f, err := n.Float64Value()
	if err != nil {
		return 0, err
	}
	return f.Float64, nil
}

// isForeignKeyViolation reports whether err is a PostgreSQL FK violation (23503).
func isForeignKeyViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23503"
}

// isInvalidTextRepresentation reports PostgreSQL enum/value cast failures (22P02).
func isInvalidTextRepresentation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "22P02"
}

func isUndefinedTableNamed(err error, tableName string) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "42P01" && strings.Contains(pgErr.Message, tableName)
}
