// Package service contains business logic for the API.
package service

import (
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/isw2-unileon/MeRenta/backend/internal/model"
	"github.com/isw2-unileon/MeRenta/backend/internal/sqlcdb"
)

var (
	// ErrInvalidCategory indicates the category value is not recognised.
	ErrInvalidCategory = errors.New("invalid category")
	// ErrAddressNotFound indicates the provided address_id does not exist.
	ErrAddressNotFound = errors.New("address not found")
	// ErrInvalidRentalPeriod indicates an invalid min/max rental-day range.
	ErrInvalidRentalPeriod = errors.New("invalid rental period")
	// ErrInvalidCondition indicates the condition value is not recognised.
	ErrInvalidCondition = errors.New("invalid condition")
)

// itemQuerier is the minimal DB interface needed by ItemService.
// It allows swapping the implementation in tests without depending on the
// full sqlcdb.Querier interface (which is regenerated by sqlc).
type itemQuerier interface {
	CreateItem(ctx context.Context, arg sqlcdb.CreateItemParams) (sqlcdb.Item, error)
	GetItemByID(ctx context.Context, itemID uuid.UUID) (sqlcdb.Item, error)
	SearchItemCards(ctx context.Context, arg sqlcdb.SearchItemCardsParams) ([]sqlcdb.SearchItemCardsRow, error)
	CountItemCardsByCategory(ctx context.Context, arg sqlcdb.CountItemCardsByCategoryParams) ([]sqlcdb.CountItemCardsByCategoryRow, error)
	CountItemCardsByCity(ctx context.Context, arg sqlcdb.CountItemCardsByCityParams) ([]sqlcdb.CountItemCardsByCityRow, error)
	CountItemCardsByCondition(ctx context.Context, arg sqlcdb.CountItemCardsByConditionParams) ([]sqlcdb.CountItemCardsByConditionRow, error)
}

// ItemService handles item listing use cases.
type ItemService struct {
	q itemQuerier
}

// NewItemService creates an ItemService with its dependencies.
func NewItemService(q itemQuerier) *ItemService {
	return &ItemService{q: q}
}

// CreateItem inserts a new item listing owned by the authenticated customer.
func (s *ItemService) CreateItem(ctx context.Context, ownerID uuid.UUID, req model.CreateItemRequest) (*model.ItemResponse, error) {
	if !isValidCategory(req.Category) {
		return nil, ErrInvalidCategory
	}
	if !isValidCondition(req.Condition) {
		return nil, ErrInvalidCondition
	}

	minDays := req.MinDays
	if minDays == 0 {
		minDays = 1
	}

	if req.MaxDays != nil && *req.MaxDays < minDays {
		return nil, ErrInvalidRentalPeriod
	}

	addressID, err := uuid.Parse(req.AddressID)
	if err != nil {
		return nil, fmt.Errorf("parsing address_id: %w", err)
	}

	pricePerDay, err := float64ToNumeric(req.PricePerDay)
	if err != nil {
		return nil, fmt.Errorf("invalid price_per_day: %w", err)
	}

	deposit, err := optionalFloat64ToNumeric(req.Deposit)
	if err != nil {
		return nil, fmt.Errorf("invalid deposit: %w", err)
	}

	maxDays, err := optionalIntToInt4(req.MaxDays)
	if err != nil {
		return nil, fmt.Errorf("invalid max_days: %w", err)
	}

	item, err := s.q.CreateItem(ctx, sqlcdb.CreateItemParams{
		OwnerID:     ownerID,
		AddressID:   addressID,
		Category:    sqlcdb.CategoryEnum(req.Category),
		Title:       req.Title,
		Description: pgtype.Text{String: req.Description, Valid: req.Description != ""},
		Brand:       pgtype.Text{String: req.Brand, Valid: req.Brand != ""},
		Model:       pgtype.Text{String: req.Model, Valid: req.Model != ""},
		Condition:   sqlcdb.ItemCondition(req.Condition),
		PricePerDay: pricePerDay,
		Deposit:     deposit,
		MinDays:     int32(minDays),
		MaxDays:     maxDays,
	})
	if err != nil {
		if isForeignKeyViolation(err) {
			return nil, ErrAddressNotFound
		}
		if isInvalidTextRepresentation(err) {
			return nil, ErrInvalidCategory
		}
		return nil, err
	}

	return toItemResponse(item)
}

// GetItem fetches a single item by its UUID.
// Returns ErrItemNotFound when the item does not exist.
func (s *ItemService) GetItem(ctx context.Context, itemID uuid.UUID) (*model.ItemResponse, error) {
	item, err := s.q.GetItemByID(ctx, itemID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrItemNotFound
		}
		return nil, err
	}

	return toItemResponse(item)
}

// SearchItems returns paginated item cards for the search page.
func (s *ItemService) SearchItems(ctx context.Context, params sqlcdb.SearchItemCardsParams, page int, limit int) (*model.SearchItemsResponse, error) {
	rows, err := s.q.SearchItemCards(ctx, params)
	if err != nil {
		return nil, err
	}

	countRows, err := s.q.CountItemCardsByCategory(ctx, sqlcdb.CountItemCardsByCategoryParams{
		RequireAvailable: params.RequireAvailable,
		Query:            params.Query,
		City:             params.City,
		Condition:        params.Condition,
		MinPrice:         params.MinPrice,
		MaxPrice:         params.MaxPrice,
	})
	if err != nil {
		return nil, err
	}

	cityRows, err := s.q.CountItemCardsByCity(ctx, sqlcdb.CountItemCardsByCityParams{
		RequireAvailable: params.RequireAvailable,
		Query:            params.Query,
		Category:         params.Category,
		Condition:        params.Condition,
		MinPrice:         params.MinPrice,
		MaxPrice:         params.MaxPrice,
	})
	if err != nil {
		return nil, err
	}

	conditionRows, err := s.q.CountItemCardsByCondition(ctx, sqlcdb.CountItemCardsByConditionParams{
		RequireAvailable: params.RequireAvailable,
		Query:            params.Query,
		Category:         params.Category,
		City:             params.City,
		MinPrice:         params.MinPrice,
		MaxPrice:         params.MaxPrice,
	})
	if err != nil {
		return nil, err
	}

	items := make([]model.SearchItemResponse, 0, len(rows))
	categoryCounts := make(map[string]int64, len(countRows))
	for _, row := range countRows {
		categoryCounts[string(row.Category)] = row.TotalCount
	}
	cityCounts := make(map[string]int64, len(cityRows))
	for _, row := range cityRows {
		cityCounts[row.City] = row.TotalCount
	}
	conditionCounts := make(map[string]int64, len(conditionRows))
	for _, row := range conditionRows {
		conditionCounts[string(row.Condition)] = row.TotalCount
	}

	var total int64
	for _, row := range rows {
		if total == 0 {
			total = row.TotalCount
		}

		pricePerDay, err := numericToFloat64(row.PricePerDay)
		if err != nil {
			return nil, fmt.Errorf("converting price_per_day: %w", err)
		}

		items = append(items, model.SearchItemResponse{
			ItemID:          row.ItemID.String(),
			OwnerID:         row.OwnerID.String(),
			AddressID:       row.AddressID.String(),
			Category:        string(row.Category),
			Title:           row.Title,
			ItemStatus:      string(row.ItemStatus),
			PricePerDay:     pricePerDay,
			IsAvailable:     row.IsAvailable,
			PublishedAt:     row.PublishedAt.Time,
			City:            row.City,
			PrimaryImageURL: row.PrimaryImageURL,
		})
	}

	return &model.SearchItemsResponse{
		Items:          items,
		Total:          total,
		Page:           page,
		Limit:          limit,
		CategoryCounts:  categoryCounts,
		CityCounts:      cityCounts,
		ConditionCounts: conditionCounts,
	}, nil
}

// toItemResponse maps a sqlcdb.Item to the API response model.
func toItemResponse(item sqlcdb.Item) (*model.ItemResponse, error) {
	pricePerDay, err := numericToFloat64(item.PricePerDay)
	if err != nil {
		return nil, fmt.Errorf("converting price_per_day: %w", err)
	}

	var deposit *float64
	if item.Deposit.Valid {
		d, err := numericToFloat64(item.Deposit)
		if err != nil {
			return nil, fmt.Errorf("converting deposit: %w", err)
		}
		deposit = &d
	}

	var maxDays *int32
	if item.MaxDays.Valid {
		maxDays = &item.MaxDays.Int32
	}

	return &model.ItemResponse{
		ItemID:      item.ItemID.String(),
		OwnerID:     item.OwnerID.String(),
		AddressID:   item.AddressID.String(),
		Category:    string(item.Category),
		Title:       item.Title,
		Description: item.Description.String,
		Brand:       item.Brand.String,
		Model:       item.Model.String,
		Condition:   string(item.Condition),
		ItemStatus:  string(item.ItemStatus),
		PricePerDay: pricePerDay,
		Deposit:     deposit,
		MinDays:     item.MinDays,
		MaxDays:     maxDays,
		IsAvailable: item.IsAvailable,
		PublishedAt: item.PublishedAt.Time,
	}, nil
}

// isValidCategory checks whether c is one of the allowed category values.
func isValidCategory(c string) bool {
	switch sqlcdb.CategoryEnum(c) {
	case sqlcdb.CategoryEnumTools,
		sqlcdb.CategoryEnumElectronics,
		sqlcdb.CategoryEnumSports,
		sqlcdb.CategoryEnumVehicles,
		sqlcdb.CategoryEnumHome,
		sqlcdb.CategoryEnumGardening,
		sqlcdb.CategoryEnumClothing,
		sqlcdb.CategoryEnumMusic,
		sqlcdb.CategoryEnumPhotography,
		sqlcdb.CategoryEnumCamping,
		sqlcdb.CategoryEnumOther:
		return true
	default:
		return false
	}
}

func isValidCondition(c string) bool {
	switch sqlcdb.ItemCondition(c) {
	case sqlcdb.ItemConditionNew,
		sqlcdb.ItemConditionLikeNew,
		sqlcdb.ItemConditionGood,
		sqlcdb.ItemConditionFair,
		sqlcdb.ItemConditionPoor:
		return true
	default:
		return false
	}
}

// float64ToNumeric converts a float64 to a valid pgtype.Numeric with 2 decimal places.
func float64ToNumeric(v float64) (pgtype.Numeric, error) {
	var n pgtype.Numeric
	err := n.Scan(strconv.FormatFloat(v, 'f', 2, 64))
	return n, err
}

// optionalFloat64ToNumeric returns an invalid (NULL) Numeric when v is nil.
func optionalFloat64ToNumeric(v *float64) (pgtype.Numeric, error) {
	if v == nil {
		return pgtype.Numeric{}, nil
	}
	return float64ToNumeric(*v)
}

func optionalIntToInt4(v *int) (pgtype.Int4, error) {
	if v == nil {
		return pgtype.Int4{}, nil
	}
	const minInt32 = -2147483648
	const maxInt32 = 2147483647
	if *v < minInt32 || *v > maxInt32 {
		return pgtype.Int4{}, fmt.Errorf("value %d overflows int32", *v)
	}
	return pgtype.Int4{Int32: int32(*v), Valid: true}, nil
}

// numericToFloat64 extracts the float64 value from a pgtype.Numeric.
func numericToFloat64(n pgtype.Numeric) (float64, error) {
	f, err := n.Float64Value()
	if err != nil {
		return 0, err
	}
	return f.Float64, nil
}

// isForeignKeyViolation reports whether err is a PostgreSQL FK violation (23503).
func isForeignKeyViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23503"
}

// isInvalidTextRepresentation reports PostgreSQL enum/value cast failures (22P02).
func isInvalidTextRepresentation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "22P02"
}
